accounts/urls.py
from django.urls import path

from accounts import views

app_name = 'accounts'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('activate/<str:uidb64>/<str:token>/', views.activate, name='activate'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('', views.dashboard, name='dashboard'),
    path('forgot_password/', views.forgot_password, name='forgot_password'),
    path('reset_password_validate/<str:uidb64>/<str:token>/', views.reset_password_validate,
         name='reset_password_validate'),
    path('reset_password/', views.reset_password, name='reset_password'),
    path('my_orders/', views.my_orders, name='my_orders'),
    path('edit_profile/', views.edit_profile, name='edit_profile'),
    path('change_password/', views.change_password, name='change_password'),
    path('order_detail/<int:order_id>/', views.order_detail, name='order_detail'),
]

cart/urls.py
from django.urls import path

from cart import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart, name='cart'),
    path('add_cart/<int:product_id>/', views.add_to_cart, name='add_cart'),
    path('remove_cart/<int:cart_item_id>/', views.remove_from_cart, name='remove_cart'),
    path('remove_cart_item/<int:cart_item_id>/', views.remove_cart_item, name='remove_cart_item'),
    path('checkout/', views.checkout, name='checkout'),
]

core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('store/', include('store.urls')),
    path('cart/', include('cart.urls')),
    path('accounts/', include('accounts.urls')),
    path('order/', include('order.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += [path('__debug__/', include('debug_toolbar.urls'))]

    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)  # for serving media files in development

accounts/models.py
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin, BaseUserManager
from django.db import models
from django.utils import timezone


class AccountManager(BaseUserManager):
    def _create_user(self, username, email, password, first_name, last_name, **extra_fields):
        """
        Create and save a user with the given username, email, and password.
        """
        if not email:
            raise ValueError('The given email must be set')
        email = self.normalize_email(email)

        if not username:
            raise ValueError('The given username must be set')

        user = self.model(username=username, email=email, first_name=first_name, last_name=last_name, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, username, email, password, first_name, last_name, **extra_fields):
        return self._create_user(username, email, password, first_name, last_name, **extra_fields)

    def create_superuser(self, username, email, password, first_name, last_name, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self._create_user(username, email, password, first_name, last_name, **extra_fields)


class Account(AbstractBaseUser, PermissionsMixin):
    first_name = models.CharField(max_length=50, blank=True)
    last_name = models.CharField(max_length=50, blank=True)
    username = models.CharField(max_length=50, unique=True)
    email = models.EmailField(max_length=100, unique=True)
    phone_number = models.CharField(max_length=50)

    # required fields
    last_login = models.DateTimeField(default=timezone.now, editable=False)
    date_joined = models.DateTimeField(default=timezone.now, editable=False)

    is_admin = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    is_superuser = models.BooleanField(default=False)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username', 'first_name', 'last_name']

    objects = AccountManager()

    def get_full_name(self):
        return f"{self.first_name} {self.last_name}"

    def __str__(self):
        return self.email


class UserProfile(models.Model):
    user = models.OneToOneField(Account, on_delete=models.CASCADE)
    address_line_1 = models.CharField(blank=True, max_length=100)
    address_line_2 = models.CharField(blank=True, max_length=100)
    profile_picture = models.ImageField(blank=True, upload_to='userprofile')
    city = models.CharField(blank=True, max_length=20)
    state = models.CharField(blank=True, max_length=20)
    country = models.CharField(blank=True, max_length=20)

    def __str__(self):
        return self.user.first_name

    def full_address(self):
        return f'{self.address_line_1} {self.address_line_2}'

accounts/forms.py
from django import forms
from django.core.exceptions import ValidationError

from accounts.models import Account, UserProfile


class RegistrationForm(forms.ModelForm):
    password1 = forms.CharField(required=True)

    class Meta:
        model = Account
        fields = ('first_name', 'last_name', 'email', 'phone_number', 'password')

    def clean_phone_number(self):
        data = self.cleaned_data.get('phone_number')

        if not data.isnumeric():
            raise ValidationError('Phone number should contain only numbers')
        if len(data) != 10:
            raise ValidationError('Phone number should 10 digits')
        if len(data) > 10:
            raise ValidationError('Phone number should not be more than 10 digits')

        return data

    def clean(self):
        super().clean()
        password = self.cleaned_data.get('password')
        password1 = self.cleaned_data.get('password1')

        if password != password1:
            raise forms.ValidationError('Passwords do not match!')


class UserForm(forms.ModelForm):
    class Meta:
        model = Account
        fields = ('first_name', 'last_name', 'phone_number')

    def __init__(self, *args, **kwargs):
        super(UserForm, self).__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs['class'] = 'form-control'


class UserProfileForm(forms.ModelForm):
    profile_picture = forms.ImageField(required=False, error_messages={'invalid': ("Image files only")},
                                       widget=forms.FileInput)

    class Meta:
        model = UserProfile
        fields = ('address_line_1', 'address_line_2', 'city', 'state', 'country', 'profile_picture')

    def __init__(self, *args, **kwargs):
        super(UserProfileForm, self).__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs['class'] = 'form-control'

accounts/views.py
import logging
from urllib.parse import urlencode, urlparse

from django.contrib import auth
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.tokens import default_token_generator
from django.contrib.sites.shortcuts import get_current_site
from django.core.mail import EmailMessage
from django.http import HttpRequest
from django.shortcuts import render, redirect, get_object_or_404
from django.template.loader import render_to_string
from django.urls import reverse
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode

from accounts.forms import RegistrationForm
from accounts.models import Account, UserProfile
from accounts.services import register_service
from cart.models import Cart, CartItem
from cart.views import _get_session_id
from order.models import Order, OrderItem
from accounts.forms import UserForm, UserProfileForm

logger = logging.getLogger(__file__)


def register(request: HttpRequest):
    form = RegistrationForm()

    if request.method == 'POST':

        form = RegistrationForm(request.POST)
        if form.is_valid():
            first_name = form.cleaned_data['first_name']
            last_name = form.cleaned_data['last_name']
            email = form.cleaned_data['email']
            phone_number = form.cleaned_data['phone_number']
            password = form.cleaned_data['password']

            user = register_service.create_inactive_account(first_name, last_name, email, phone_number, password)

            user.save()

            # Create a user profile
            profile = UserProfile()
            profile.user_id = user.id
            profile.profile_picture = 'default/default-user.png'
            profile.save()

            current_site = get_current_site(request)
            email_subject = 'Activate your account'
            email_body = render_to_string('accounts/account_verification_email.html',
                                          {
                                              'user': user,
                                              'domain': current_site,
                                              'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                                              'token': default_token_generator.make_token(user)
                                          })

            email_message = EmailMessage(email_subject, email_body, to=[user.email])
            email_message.send()
            logger.info('Verification email sent.')

            base_url = reverse('accounts:login')
            query_string = urlencode({
                'command': 'validation',
                'email': user.email
            })
            url = f"{base_url}?{query_string}"
            return redirect(url)

    context = {
        'form': form
    }

    return render(request, 'accounts/register.html', context)


def login(request: HttpRequest):
    if request.user.is_authenticated:
        return redirect('accounts:dashboard')

    if request.method == 'POST':
        email = request.POST.get('email')
        password = request.POST.get('password')

        user = auth.authenticate(email=email, password=password)
        if user:
            # assign anonymous cart to user
            try:
                # get cart items and their variation in current session cart
                cart = Cart.objects.get(cart_id=_get_session_id(request))
                new_cart_items = cart.cart_items.all().prefetch_related('variations')

                new_cart_item_variations = []
                new_cart_items_ids = []
                for new_cart_item in new_cart_items:
                    new_cart_item_variations.append(list(new_cart_item.variations.all()))
                    new_cart_items_ids.append(new_cart_item)

                # get all the items from user's already existing cart
                user_cart_items = CartItem.objects.filter(buyer=user).prefetch_related('variations')
                existing_items = []
                existing_item_ids = []
                for user_cart_item in user_cart_items:
                    existing_items.append(list(user_cart_item.variations.all()))
                    existing_item_ids.append(user_cart_item)

                # find if current cart item is in user's cart, if yes increment else assign user
                for idx, item in enumerate(new_cart_item_variations):
                    if item in existing_items:
                        existing_id = existing_items.index(item)
                        existing_item = existing_item_ids[existing_id]
                        item = new_cart_items_ids[idx]
                        existing_item.quantity += item.quantity
                        existing_item.save()
                    else:
                        item = new_cart_items_ids[idx]
                        item.buyer = user
                        item.save()

            except Cart.DoesNotExist:
                logger.exception('Cart does not exists')

            auth.login(request, user)

            referer_url = request.META.get('HTTP_REFERER')
            query = urlparse(referer_url).query
            logger.info(f"Query {query} {referer_url}")
            query_params = dict(q.split('=') for q in query.split('&') if q)

            if 'next' in query_params:
                return redirect(query_params['next'])

            messages.success(request, 'You are logged in.')
            return redirect('accounts:dashboard')
        else:
            messages.error(request, "Incorrect username or password")
            return redirect('accounts:login')

    return render(request, 'accounts/login.html')


@login_required
def logout(request: HttpRequest):
    auth.logout(request)
    messages.success(request, 'You are logged out. Login again!')
    return redirect('accounts:login')


def activate(request: HttpRequest, uidb64: str, token: str):
    user = None
    try:
        userid = urlsafe_base64_decode(uidb64).decode()
        user = Account._default_manager.get(pk=userid)
    except (ValueError, TypeError, OverflowError, Account.DoesNotExist) as e:
        logger.exception('Error')
        user = None

    if user and default_token_generator.check_token(user, token):
        user.is_active = True
        user.save()
        messages.success(request, 'Your account is activated')
        logger.info('Account activated')
        return redirect('accounts:login')
    else:
        messages.error(request, 'Invalid verification url!')
        return redirect('accounts:register')


@login_required
def dashboard(request: HttpRequest):
    orders = Order.objects.filter(user=request.user, is_ordered=True).order_by('-created_at')
    orders_count = orders.count()
    context = {
        'orders_count': orders_count
    }
    return render(request, 'accounts/dashboard.html', context)


def forgot_password(request: HttpRequest):
    if request.method == 'POST':
        email = request.POST.get('email')
        try:
            user = Account.objects.get(email__exact=email)

            # send password reset email
            current_site = get_current_site(request)
            email_subject = 'Reset your password'
            email_body = render_to_string('accounts/reset_password_email.html',
                                          {
                                              'user': user,
                                              'domain': current_site,
                                              'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                                              'token': default_token_generator.make_token(user)
                                          })

            email_message = EmailMessage(email_subject, email_body, to=[user.email])
            email_message.send()
            messages.success(request, 'Password reset email sent to your email.')
            return redirect('accounts:login')

        except Account.DoesNotExist as e:
            messages.error(request, 'Account does not exist. Please check and type again')

    return render(request, 'accounts/forgot_password.html')


def reset_password_validate(request: HttpRequest, uidb64: str, token: str):
    user = None
    try:
        userid = urlsafe_base64_decode(uidb64).decode()
        user = Account._default_manager.get(pk=userid)
        print(user)
        # return retype password form
    except (ValueError, TypeError, OverflowError, Account.DoesNotExist) as e:
        logger.exception('Error')
        user = None

    if user and default_token_generator.check_token(user, token):
        request.session['uid'] = user.id
        return render(request, 'accounts/reset_password.html')

    messages.error(request, 'Invalid password reset link.')
    return redirect("accounts:login")


def reset_password(request: HttpRequest):
    if request.method == 'POST':
        password = request.POST.get('password')
        password1 = request.POST.get('password1')

        if password == password1:
            uid = request.session.get('uid')
            if uid:
                user = Account.objects.get(pk=uid)
                user.set_password(password)
                user.save()

                del request.session['uid']

                messages.success(request, 'Password successfully changed')
                return redirect('accounts:login')
            else:
                messages.error(request, 'Invalid password reset request')
                return redirect('accounts:forgot_password')

        messages.error(request, 'Passwords did not match!')

    return render(request, 'accounts/reset_password.html')


def my_orders(request: HttpRequest):
    orders = Order.objects.filter(user=request.user, is_ordered=True).order_by('-created_at')
    context = {
        'orders': orders
    }
    return render(request, 'accounts/my_orders.html', context)


@login_required

templates/accounts/account_verification_email.html
{% autoescape off %}
  Hi {{ user.first_name }},
  Please click on the below link to activate your account.
  http://{{ domain }}{% url 'accounts:activate' uidb64=uid token=token %}

  If you think it's not you, please ignore this email.
{% endautoescape %}

templates/accounts/change_password.html
{% extends 'base.html' %}


{% block content %}

<section class="section-content padding-y bg">

{% include 'includes/alerts.html' %}
<div class="container">
	<div class="row">
	{% include 'includes/dashboard_sidebar.html' %}
	<main class="col-md-9">
		<article class="card">
		<header class="card-header">
			<strong class="d-inline-block mr-3">Change Your Password</strong>

		</header>
		<div class="card-body">
			<div class="row">
			<div class="col-md-12">
				<form action="{% url 'accounts:change_password' %}" method="POST">
					{% csrf_token %}

					<div class="form-group">
						<label>Current Password</label>
						<input type="password" name="current_password" placeholder="Current Password" class="form-control" required>
					</div>
					<div class="form-group">
						<label>Create new password</label>
						<input type="password" name="new_password" placeholder="Create New Password" class="form-control" required>
					</div>
					<div class="form-group">
						<label>Confirm new password</label>
						<input type="password" name="confirm_password" placeholder="Confirm New Password" class="form-control" required>
					</div>

					<input type="submit" value="Submit" class="btn btn-primary">
				</form>
			</div>

			</div> <!-- row.// -->
		</div> <!-- card-body .// -->

		</article> <!-- order-group.// -->
	</main>
</div> <!-- row.// -->
</div>


</section>

{% endblock %}

templates/accounts/dashboard.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
  <!-- ========================= SECTION CONTENT ========================= -->
  <section class="section-content padding-y bg">

    <div class="container">
      {% include 'includes/alerts.html' %}

      <div class="row">
        {% include 'includes/dashboard_sidebar.html' %}

        <main class="col-md-9">
          <article class="card">
            <header class="card-header">
              <strong class="d-inline-block mr-3">Logged in as:</strong>
              <span>{{ user.get_full_name }}</span>
            </header>
            <div class="card-body">
              <div class="row">

                <div class="col-md-6">
                  <div class="card" style="text-align: center">
                    <div class="card-body">
                      <h5 class="card-title">Total Orders</h5>
                      <h4>{{ orders_count }}</h4>
                      <a href="">View Orders</a>
                    </div>
                  </div>
                </div>
                <div class="col-md-6">
                  <div class="card" style="text-align: center">
                    <div class="card-body">
                      <img src="https://www.w3schools.com/howto/img_avatar.png" alt="User Profile Picture" height="50" width="50" style="border-radius: 50%">
                      <p class="mb-0">{{ user.email }}</p>
                      <p>{{ user.phone_number }}</p>
                    </div>
                  </div>
                </div>
              </div> <!-- row.// -->
            </div> <!-- card-body .// -->

          </article> <!-- order-group.// -->
        </main>
      </div> <!-- row.// -->
    </div>


  </section>
  <!-- ========================= SECTION CONTENT END// ========================= -->
{% endblock %}

templates/accounts/edit_profile.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
  <!-- ========================= SECTION CONTENT ========================= -->
  <section class="section-content padding-y bg">

    <div class="container">
      {% include 'includes/alerts.html' %}

      <div class="row">
        {% include 'includes/dashboard_sidebar.html' %}

        <main class="col-md-9">
          <article class="card">
            <header class="card-header">
              <strong class="d-inline-block mr-3">Edit Profile</strong>
            </header>
            <div class="card-body">
              <div class="text-right">
                <img src="{{ userprofile.profile_picture.url }}" alt="Profile Picture" width="100"
                     style="border-radius:50px;">
              </div>
              <div class="row">
                <div class="col-md-12">
                  <form action="{% url 'accounts:edit_profile' %}" method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="form-row">
                      <div class="form-group col-md-6">
                        <label>First Name</label>
                        {{ user_form.first_name }}
                      </div>
                      <div class="form-group col-md-6">
                        <label>Last Name</label>
                        {{ user_form.last_name }}
                      </div>
                    </div>
                    <div class="form-row">
                      <div class="form-group col-md-6">
                        <label>Phone Number</label>
                        {{ user_form.phone_number }}
                      </div>
                      <div class="form-group col-md-6">
                        <label>Profile Picture</label>
                        {{ profile_form.profile_picture }}
                      </div>
                    </div>
                    <div class="form-group">
                      <label>Address Line 1</label>
                      {{ profile_form.address_line_1 }}
                    </div>
                    <div class="form-group">
                      <label>Address Line 2</label>
                      {{ profile_form.address_line_2 }}
                    </div>
                    <div class="form-row">
                      <div class="form-group col-md-4">
                        <label>City</label>
                        {{ profile_form.city }}
                      </div>
                      <div class="form-group col-md-4">
                        <label>State</label>
                        {{ profile_form.state }}
                      </div>
                      <div class="form-group col-md-4">
                        <label>Country</label>
                        {{ profile_form.country }}
                      </div>
                    </div>
                    <input type="submit" value="Save" class="btn btn-primary">
                  </form>
                </div>


              </div> <!-- row.// -->
            </div> <!-- card-body .// -->

          </article> <!-- order-group.// -->
        </main>
      </div> <!-- row.// -->
    </div>


  </section>
  <!-- ========================= SECTION CONTENT END// ========================= -->
{% endblock %}

templates/accounts/forgot_password.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
  <!-- ========================= SECTION CONTENT ========================= -->
  <section class="section-content padding-y" style="min-height:80vh">

    <!-- ============================ COMPONENT LOGIN   ================================= -->


    <div class="card mx-auto" style="max-width: 380px; margin-top:100px;">

      <div class="card-body">
        <h4 class="card-title mb-4">Forgot Password</h4>

        {% include 'includes/alerts.html' %}

        <ul>
          {% for non_field_error in form.non_field_errors %}
            <li class="text-danger">{{ non_field_error }}</li>
          {% endfor %}
        </ul>

        {% for hidden_field in form.hidden_fields %}
          {{ hidden_field.errors }}
          {{ hidden_field }}
        {% endfor %}

        <form action="{% url 'accounts:forgot_password' %}" method="post">
          {% csrf_token %}

          <div class="form-group">
            <input
                type="email"
                name="email"
                class="form-control"
                placeholder="Email Address"
                required>

            {% for error in form.email.errors %}
              <div class="invalid-feedback d-block text-end">{{ error }}</div>
            {% endfor %}

          </div> <!-- form-group// -->

          <div class="form-group">
            <a href="{% url 'accounts:login' %}" class="float-right">Got password? Login</a>
          </div> <!-- form-group form-check .// -->

          <div class="form-group">
            <button type="submit" class="btn btn-primary btn-block"> Submit</button>
          </div> <!-- form-group// -->

        </form>
      </div> <!-- card-body.// -->
    </div> <!-- card .// -->

    <p class="text-center mt-4">Don't have account? <a href="{% url 'accounts:register' %}">Sign up</a></p>
    <br><br>

    <!-- ============================ COMPONENT LOGIN  END.// ================================= -->


  </section>
  <!-- ========================= SECTION CONTENT END// ========================= -->
{% endblock %}

templates/accounts/logout.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
  <h2>logout</h2>
{% endblock %}

templates/accounts/my_orders.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
  <!-- ========================= SECTION CONTENT ========================= -->
  <section class="section-content padding-y bg">

    <div class="container">
      {% include 'includes/alerts.html' %}

      <div class="row">
        {% include 'includes/dashboard_sidebar.html' %}

        <main class="col-md-9">
          <article class="card">
            <header class="card-header">
              <strong class="d-inline-block mr-3">Order History</strong>
            </header>
            <div class="card-body">
              <div class="row">

                <table class="table table-hover">
                  <thead>
                  <tr>
                    <th scope="col">Order #</th>
                    <th scope="col">Billing Name</th>
                    <th scope="col">Phone</th>
                    <th scope="col">Order Total</th>
                    <th scope="col">Date</th>
                  </tr>
                  </thead>
                  <tbody>
                  {% for order in orders %}
                    <tr>
                    <th scope="row"><a href="{% url 'accounts:order_detail' order.order_number %}">{{ order.order_number }}</th>
                    <td>{{ order.first_name }} {{ order.lastname }}</td>
                    <td>{{ order.phone_number }}</td>
                    <td>${{ order.order_total }}</td>
                    <td>{{ order.created_at }}</td>
                  </tr>
                  {% endfor %}

                  </tbody>
                </table>

              </div> <!-- row.// -->
            </div> <!-- card-body .// -->

          </article> <!-- order-group.// -->
        </main>
      </div> <!-- row.// -->
    </div>


  </section>
  <!-- ========================= SECTION CONTENT END// ========================= -->
{% endblock %}

templates/accounts/reset_password.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
  <!-- ========================= SECTION CONTENT ========================= -->
  <section class="section-content padding-y" style="min-height:80vh">

    <!-- ============================ COMPONENT LOGIN   ================================= -->


    <div class="card mx-auto" style="max-width: 380px; margin-top:100px;">

      <div class="card-body">
        <h4 class="card-title mb-4">Reset Password</h4>

        {% include 'includes/alerts.html' %}

        <ul>
          {% for non_field_error in form.non_field_errors %}
            <li class="text-danger">{{ non_field_error }}</li>
          {% endfor %}
        </ul>

        {% for hidden_field in form.hidden_fields %}
          {{ hidden_field.errors }}
          {{ hidden_field }}
        {% endfor %}

        <form action="{% url 'accounts:reset_password' %}" method="post">
          {% csrf_token %}

          <div class="form-group">
            <input
                type="password"
                name="password"
                class="form-control"
                placeholder="Password"
                required>
          </div> <!-- form-group// -->

          <div class="form-group">
            <input
                type="password"
                name="password1"
                class="form-control"
                placeholder="Confirm Password"
                required>
          </div> <!-- form-group// -->


          <div class="form-group">
            <button type="submit" class="btn btn-primary btn-block"> Submit</button>
          </div> <!-- form-group// -->

        </form>
      </div> <!-- card-body.// -->
    </div> <!-- card .// -->

    <p class="text-center mt-4">Don't have account? <a href="{% url 'accounts:register' %}">Sign up</a></p>
    <br><br>

    <!-- ============================ COMPONENT LOGIN  END.// ================================= -->


  </section>
  <!-- ========================= SECTION CONTENT END// ========================= -->
{% endblock %}

templates/accounts/reset_password_email.html
{% autoescape off %}
  Hi {{ user.first_name }},
  Please click on the below link to reset your password.
  http://{{ domain }}{% url 'accounts:reset_password_validate' uidb64=uid token=token %}

  If you think it's not you, please ignore this email.

{% endautoescape %}