accounts/urls.py
from django.urls import path

from accounts import views

app_name = 'accounts'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('activate/<str:uidb64>/<str:token>/', views.activate, name='activate'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('', views.dashboard, name='dashboard'),
    path('forgot_password/', views.forgot_password, name='forgot_password'),
    path('reset_password_validate/<str:uidb64>/<str:token>/', views.reset_password_validate,
         name='reset_password_validate'),
    path('reset_password/', views.reset_password, name='reset_password'),
    path('my_orders/', views.my_orders, name='my_orders'),
    path('edit_profile/', views.edit_profile, name='edit_profile'),
    path('change_password/', views.change_password, name='change_password'),
    path('order_detail/<int:order_id>/', views.order_detail, name='order_detail'),
]

cart/urls.py
from django.urls import path

from cart import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart, name='cart'),
    path('add_cart/<int:product_id>/', views.add_to_cart, name='add_cart'),
    path('remove_cart/<int:cart_item_id>/', views.remove_from_cart, name='remove_cart'),
    path('remove_cart_item/<int:cart_item_id>/', views.remove_cart_item, name='remove_cart_item'),
    path('checkout/', views.checkout, name='checkout'),
]

core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('store/', include('store.urls')),
    path('cart/', include('cart.urls')),
    path('accounts/', include('accounts.urls')),
    path('order/', include('order.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += [path('__debug__/', include('debug_toolbar.urls'))]

    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)  # for serving media files in development

order/urls.py
from django.urls import path

from order import views

app_name = 'order'

urlpatterns = [
    path('place_order/', views.place_order, name='place_order'),
    path('payment/', views.payment, name='payment'),
    path('order_complete/', views.order_complete, name='order_complete'),
]

store/urls.py
from django.urls import path

from . import views

app_name = 'store'

urlpatterns = [
    path('', views.store, name='store'),
    path('category/<slug:category_slug>/', views.store, name='products_by_category'),
    path('category/<slug:category_slug>/<slug:product_slug>/', views.product_detail, name='product_detail'),
    path('search/', views.search_products, name='search_products'),
    path('submit_review/<int:product_id>', views.submit_review, name='submit_review')
]

cart/models.py
from django.db import models
# Create your models here.
from django.utils import timezone

from accounts.models import Account
from store.models import Product, Variation


class Cart(models.Model):
    cart_id = models.CharField(max_length=256, blank=True)
    date_added = models.DateTimeField(default=timezone.now, editable=False)

    def __str__(self):
        return self.cart_id


class CartItem(models.Model):
    buyer = models.ForeignKey(Account, on_delete=models.CASCADE, null=True)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    variations = models.ManyToManyField(Variation, blank=True)
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE, related_name='cart_items', null=True)
    quantity = models.IntegerField()
    is_active = models.BooleanField(default=True)

    def sub_total(self):
        return self.quantity * self.product.price

    def __str__(self):
        return f"{self.product.product_name}"

store/models.py
from django.db import models
from django.db.models import Avg, Count
from django.urls import reverse
from django.utils import timezone

from accounts.models import Account
from category.models import Category


class Product(models.Model):
    product_name = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(max_length=200, unique=True)
    description = models.TextField(max_length=500, blank=True)
    price = models.IntegerField()
    product_images = models.ImageField(upload_to='photos/products')
    stock = models.IntegerField()
    is_available = models.BooleanField(default=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    created_at = models.DateTimeField(default=timezone.now, editable=False)
    modified_at = models.DateTimeField(auto_now=True)

    def get_url(self):
        return reverse('store:product_detail', args=[self.category.slug, self.slug])

    def average_rating(self):
        reviews = ReviewRating.objects.filter(product=self, status=True).aggregate(average=Avg('rating'))
        average = 0
        if reviews['average']:
            average = float(reviews['average'])
        return average

    def total_rating(self):
        reviews = ReviewRating.objects.filter(product=self, status=True).aggregate(count=Count('rating'))
        count = 0
        if reviews['count']:
            count = int(reviews['count'])
        return count

    def __str__(self):
        return self.product_name


class VariationManager(models.Manager):
    def colors(self):
        return super().filter(variation_category='color', is_active=True)

    def sizes(self):
        return super().filter(variation_category='size', is_active=True)


variation_choices = (
    ('color', 'color'),
    ('size', 'size')
)


class Variation(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='variations')
    variation_category = models.CharField(max_length=200, choices=variation_choices)
    variation_value = models.CharField(max_length=200)
    is_active = models.BooleanField(default=True)
    created_at = models.DateTimeField(default=timezone.now)

    objects = VariationManager()

    class Meta:
        ordering = ('variation_category',)

    def __str__(self):
        return f"{self.variation_category} - {self.variation_value}"


class ReviewRating(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    user = models.ForeignKey(Account, on_delete=models.CASCADE)
    subject = models.CharField(max_length=100, blank=True)
    review = models.CharField(max_length=500, blank=True)
    rating = models.FloatField()
    ip = models.CharField(max_length=20, blank=True)
    status = models.BooleanField(default=True)
    created_at = models.DateTimeField(default=timezone.now)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.subject

store/forms.py
from django import forms

from accounts.models import UserProfile, Account
from store.models import ReviewRating


class ReviewRatingForm(forms.ModelForm):
    class Meta:
        model = ReviewRating
        fields = ['subject', 'review', 'rating']

cart/views.py
from django.contrib.auth.decorators import login_required
from django.core.exceptions import ObjectDoesNotExist
from django.http import HttpRequest
from django.shortcuts import render, redirect, get_object_or_404

from cart.models import Cart, CartItem
from cart.services import cart_service


def _get_session_id(request: HttpRequest):
    session_id = request.session.session_key
    if not session_id:
        session_id = request.session.create()
    return session_id


def add_to_cart(request: HttpRequest, product_id: int):
    cart_service.add_item_to_cart(request, product_id)

    return redirect('cart:cart')


def remove_from_cart(request: HttpRequest, cart_item_id: int):
    current_user = request.user

    if current_user.is_authenticated:
        cart_item = CartItem.objects.get(id=cart_item_id, buyer=current_user)
    else:
        cart = get_object_or_404(Cart, cart_id=_get_session_id(request))
        cart_item = CartItem.objects.get(id=cart_item_id, cart=cart)

    if cart_item.quantity > 1:
        cart_item.quantity -= 1
        cart_item.save()
    else:
        cart_item.delete()

    return redirect('cart:cart')


def remove_cart_item(request: HttpRequest, cart_item_id: int):
    current_user = request.user

    if current_user.is_authenticated:
        cart_item = CartItem.objects.get(id=cart_item_id, buyer=current_user)
    else:
        cart = get_object_or_404(Cart, cart_id=_get_session_id(request))
        cart_item = get_object_or_404(CartItem, id=cart_item_id, cart=cart)

    cart_item.delete()

    return redirect('cart:cart')


def cart(request: HttpRequest):
    quantity = 0
    total = 0
    grand_total = 0
    tax = 0
    cart_items = None

    try:
        if request.user.is_authenticated:
            cart_items = CartItem.objects.filter(buyer=request.user, is_active=True).prefetch_related('variations',
                                                                                                      'product')
        else:
            cart = Cart.objects.get(cart_id=_get_session_id(request))
            # reduced 30 queries to 9 with prefetch_related
            cart_items = CartItem.objects.filter(cart=cart, is_active=True).prefetch_related('variations', 'product')

        for item in cart_items:
            total += (item.quantity * item.product.price)
            quantity += item.quantity
        tax = (2 * total) / 100  # 2% tax , move to db
        grand_total = total + tax
    except ObjectDoesNotExist as ode:
        print(ode)

    context = {
        'total': total,
        'quantity': quantity,
        'cart_items': cart_items,
        'tax': tax,
        'grand_total': grand_total
    }

    return render(request, 'store/cart.html', context=context)


@login_required
def checkout(request: HttpRequest):
    quantity = 0
    total = 0
    grand_total = 0
    tax = 0
    cart_items = None

    try:
        if request.user.is_authenticated:
            cart_items = CartItem.objects.filter(buyer=request.user, is_active=True).prefetch_related('variations',
                                                                                                      'product')
        else:
            cart = Cart.objects.get(cart_id=_get_session_id(request))
            # reduced 30 queries to 9 with prefetch_related
            cart_items = CartItem.objects.filter(cart=cart, is_active=True).prefetch_related('variations', 'product')

        for item in cart_items:
            total += (item.quantity * item.product.price)
            quantity += item.quantity
        tax = (2 * total) / 100  # 2% tax , move to db
        grand_total = total + tax
    except ObjectDoesNotExist as ode:
        print(ode)

    context = {
        'total': total,
        'quantity': quantity,
        'cart_items': cart_items,
        'tax': tax,
        'grand_total': grand_total
    }
    return render(request, 'store/checkout.html', context)

store/views.py
import logging

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.db.models import Q
from django.http import HttpRequest
from django.shortcuts import render, redirect

from category.models import Category
from order.models import OrderItem
from store.forms import ReviewRatingForm
from store.models import Product, ReviewRating

logger = logging.getLogger(__file__)


def store(request: HttpRequest, category_slug: str = None):
    products = None
    product_count = None

    if category_slug:
        category = Category.objects.get(slug=category_slug)
        products = Product.objects.filter(category=category, is_available=True).order_by('id')
        product_count = products.count()
    else:
        products = Product.objects.filter(is_available=True).order_by('id')
        product_count = products.count()

    paginator = Paginator(products, 6)
    page_num = request.GET.get('page')
    paged_products = paginator.get_page(page_num)

    context = {'products': paged_products, 'product_count': product_count}

    return render(request, 'store/store.html', context)


def product_detail(request: HttpRequest, category_slug, product_slug):
    product = None
    try:
        product = Product.objects.get(category__slug=category_slug, slug=product_slug)
        # is_product_in_cart = CartItem.objects.filter(cart__cart_id=_get_session_id(request), product=product).exists()
    except Product.DoesNotExist as ex:
        raise ex

    order_item = None
    if request.user.is_authenticated:
        try:
            order_item = OrderItem.objects.filter(user=request.user, product=product).exists()
        except OrderItem.DoesNotExist as ex:
            logger.exception(ex)

    reviews = ReviewRating.objects.filter(product=product, status=True)

    context = {
        'product': product,
        # 'is_product_in_cart': is_product_in_cart,
        'order_item': order_item,
        'reviews': reviews
    }

    return render(request, 'store/product_detail.html', context)


def search_products(request: HttpRequest):
    keyword = request.GET.get('keyword')
    products = Product.objects.order_by('-created_at').filter(
        Q(description__icontains=keyword) | Q(product_name__icontains=keyword))
    product_count = products.count()
    context = {
        'products': products,
        'product_count': product_count
    }
    return render(request, 'store/store.html', context)


@login_required
def submit_review(request: HttpRequest, product_id: int):
    url = request.META.get('HTTP_REFERER')
    if request.method == 'POST':
        try:
            review = ReviewRating.objects.get(user__id=request.user.id, product__id=product_id)
            form = ReviewRatingForm(request.POST, instance=review)
            form.save()
            messages.success(request, "Thank you for your review")
            return redirect(url)
        except ReviewRating.DoesNotExist:
            logger.warning('Review does not exists')
            form = ReviewRatingForm(request.POST)
            if form.is_valid():
                data = ReviewRating()
                data.subject = form.cleaned_data['subject']
                data.review = form.cleaned_data['review']
                data.rating = form.cleaned_data['rating']
                data.ip = request.META.get('REMOTE_ADDR')
                data.user = request.user
                data.product_id = product_id
                data.save()
                messages.success(request, "Thank you for your review")
                return redirect(url)

templates/store/cart.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
  <section class="section-content padding-y bg">
    <div class="container">

      <!-- ============================ COMPONENT 1 ================================= -->


      {% if not cart_items %}
        <div>
          <h2 class="text-center">Your shopping cart is empty</h2>
        </div>
        <br>
        <div class="text-center">
          <a href="{% url 'store:store' %}" class="btn btn-primary">Continue Shopping</a>
        </div>

      {% else %}
        <div class="row">
          <aside class="col-lg-9">
            <div class="card">
              <table class="table table-borderless table-shopping-cart">
                <thead class="text-muted">
                <tr class="small text-uppercase">
                  <th scope="col">Product</th>
                  <th scope="col" width="120">Quantity</th>
                  <th scope="col" width="120">Price</th>
                  <th scope="col" class="text-right" width="200"></th>
                </tr>
                </thead>
                <tbody>
                {% for cart_item in cart_items %}

                  <tr>
                    <td>
                      <figure class="itemside align-items-center">
                        <div class="aside"><img src="{{ cart_item.product.product_images.url }}" class="img-sm"></div>
                        <figcaption class="info">
                          <a href="{{ cart_item.product.get_url }}"
                             class="title text-dark">{{ cart_item.product.product_name }}</a>
                          {% for variation in cart_item.variations.all %}
                            <p class="text-muted small">{{ variation.variation_category | capfirst }}: {{ variation.variation_value | capfirst }}
                              <br></p>
                          {% endfor %}
                        </figcaption>
                      </figure>
                    </td>
                    <td>
                      <!-- col.// -->
                      <div class="col">
                        <div class="input-group input-spinner">
                          <div class="input-group-prepend">
                            <a href="{% url 'cart:remove_cart' cart_item.id %}" class="btn btn-light"
                               type="button" id="button-plus"><i class="fa fa-minus"></i>
                            </a>
                          </div>
                          <input type="text" class="form-control" value="{{ cart_item.quantity }}">
                          <div class="input-group-append">
                            <form action="{% url 'cart:add_cart' cart_item.product.id %}" method="post">
                              {% csrf_token %}
                              {% for variation in cart_item.variations.all %}
                                <input type="hidden" name="{{ variation.variation_category | lower }}"
                                       value="{{ variation.variation_value | capfirst }}">
                              {% endfor %}
                              <button class="btn btn-light" type="submit" id="button-minus"><i class="fa fa-plus"></i>
                              </button>
                            </form>

                          </div>
                        </div> <!-- input-group.// -->
                      </div> <!-- col.// -->
                    </td>
                    <td>
                      <div class="price-wrap">
                        <var class="price">${{ cart_item.sub_total }}</var>
                        <small class="text-muted"> ${{ cart_item.product.price }} each </small>
                      </div> <!-- price-wrap .// -->
                    </td>
                    <td class="text-right">
                      <a href="{% url 'cart:remove_cart_item' cart_item.id %}" class="btn btn-danger"
                         onclick="return confirm('Are you sure you want to delete this item?')">
                        Remove</a>
                    </td>
                  </tr>

                {% endfor %}
                </tbody>
              </table>
            </div> <!-- card.// -->

          </aside> <!-- col.// -->

          <aside class="col-lg-3">

            <div class="card">
              <div class="card-body">
                <dl class="dlist-align">
                  <dt>Total price:</dt>
                  <dd class="text-right">${{ total }}</dd>
                </dl>
                <dl class="dlist-align">
                  <dt>Tax:</dt>
                  <dd class="text-right"> ${{ tax }}</dd>
                </dl>
                <dl class="dlist-align">
                  <dt>Total:</dt>
                  <dd class="text-right text-dark b"><strong>${{ grand_total }}</strong></dd>
                </dl>
                <hr>
                <p class="text-center mb-3">
                  <img src="{% static 'images/misc/payments.png' %}" height="26">
                </p>
                <a href="{% url 'cart:checkout' %}" class="btn btn-primary btn-block"> Checkout </a>
                <a href="{% url 'store:store' %}" class="btn btn-light btn-block">Continue Shopping</a>
              </div> <!-- card-body.// -->
            </div> <!-- card.// -->

          </aside> <!-- col.// -->


        </div> <!-- row.// -->
      {% endif %}
      <!-- ============================ COMPONENT 1 END .// ================================= -->

    </div> <!-- container .//  -->
  </section>
  <!-- ========================= SECTION CONTENT END// ========================= -->
{% endblock %}

templates/store/checkout.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
  <section class="section-content padding-y bg">
    <div class="container">

      <!-- ============================ COMPONENT 1 ================================= -->
      <form action="{% url 'order:place_order' %}" method="post">
        {% csrf_token %}
        <div class="row">


          <aside class="col-md-7">

            <div class="card">
              <div class="card-header text-center">
                <h3>Shipping Address</h3>
              </div>

              <div class="card-body">
                {% include 'includes/alerts.html' %}

                <div class="form-row">
                  <div class="col form-group">
                    <label for="">First Name</label>
                    <input type="text" name="first_name" class="form-control" required>
                  </div>
                  <div class="col form-group">
                    <label for="">Last Name</label>
                    <input type="text" name="last_name" class="form-control" required>
                  </div>
                </div>

                <div class="form-row">
                  <div class="col form-group">
                    <label for="">Email</label>
                    <input type="email" name="email" class="form-control" required>
                  </div>
                  <div class="col form-group">
                    <label for="">Phone Number</label>
                    <input type="text" name="phone" class="form-control" maxlength="10" required>
                  </div>
                </div>

                <div class="form-row">
                  <div class="col form-group">
                    <label for="">Address Line 1</label>
                    <input type="text" name="address_line_1" class="form-control" required>
                  </div>
                  <div class="col form-group">
                    <label for="">Address Line 2</label>
                    <input type="text" name="address_line_2" class="form-control" required>
                  </div>
                </div>

                <div class="form-row">
                  <div class="col form-group">
                    <label for="">City</label>
                    <input type="text" name="city" class="form-control" required>
                  </div>
                  <div class="col form-group">
                    <label for="">State</label>
                    <input type="text" name="state" class="form-control" required>
                  </div>
                  <div class="col form-group">
                    <label for="">Country</label>
                    <input type="text" name="country" class="form-control" required>
                  </div>
                </div>

                <div class="form-row">
                  <div class="col form-group">
                    <label for="">Order Note</label>
                    <textarea name="order_note" class="form-control"></textarea>
                  </div>

                </div>


              </div> <!-- card-body.// -->
            </div> <!-- card.// -->

          </aside> <!-- col.// -->


          <aside class="col-md-5">
            <div class="card">
              <table class="table table-borderless table-shopping-cart">
                <thead class="text-muted">
                <tr class="small text-uppercase">
                  <th scope="col">Product</th>
                  <th scope="col" width="120">Quantity</th>
                  <th scope="col" width="120">Price</th>

                </tr>
                </thead>

                <tbody>
                {% for cart_item in cart_items %}
                  <tr>
                    <td>
                      <figure class="itemside align-items-center">
                        <div class="aside"><img src="{{ cart_item.product.product_images.url }}" class="img-sm"></div>
                        <figcaption class="info">
                          <a href="{{ cart_item.product.get_url }}"
                             class="title text-dark">{{ cart_item.product.product_name }}</a>
                          {% for variation in cart_item.variations.all %}
                            <p class="text-muted small">{{ variation.variation_category | capfirst }}: {{ variation.variation_value | capfirst }}
                              <br></p>
                          {% endfor %}
                        </figcaption>
                      </figure>
                    </td>
                    <td>
                      <!-- col.// -->
                      <div class="col">
                        <div class="text-center">
                          {{ cart_item.quantity }}
                        </div> <!-- input-group.// -->
                      </div> <!-- col.// -->
                    </td>
                    <td>
                      <div class="price-wrap">
                        <var class="price">${{ cart_item.sub_total }}</var>
                        <small class="text-muted"> ${{ cart_item.product.price }} each </small>
                      </div> <!-- price-wrap .// -->
                    </td>
                  </tr>
                {% endfor %}
                </tbody>
                <tfoot>
                <tr class="text-uppercase">
                  <td>
                    <div class="text-center "><strong>Total</strong></div>
                  </td>
                  <td><!-- col.// -->
                    <div class="col">
                      <div class="text-center">
                        {{ quantity }}
                      </div> <!-- input-group.// -->
                    </div> <!-- col.// --></td>
                  <td>
                    <div class="price-wrap">
                      <var class="price">${{ total }}</var>
                    </div> <!-- price-wrap .// -->
                  </td>
                </tr>
                </tfoot>
              </table>
              <hr>
              <div class="mx-3 mb-2">
                <p class="text-center mb-3">
                  <img src="{% static 'images/misc/payments.png' %}" height="26">
                </p>
                <button class="btn btn-primary btn-block"> Place Order</button>
                <a href="{% url 'store:store' %}" class="btn btn-light btn-block">Continue Shopping</a>
              </div>

            </div> <!-- card.// -->

          </aside> <!-- col.// -->


        </div> <!-- row.// -->
      </form>

      <!-- ============================ COMPONENT 1 END .// ================================= -->

    </div> <!-- container .//  -->
  </section>
  <!-- ========================= SECTION CONTENT END// ========================= -->
{% endblock %}