cart/urls.py
from django.urls import path

from cart import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart, name='cart'),
    path('add_cart/<int:product_id>/', views.add_to_cart, name='add_cart'),
    path('remove_cart/<int:cart_item_id>/', views.remove_from_cart, name='remove_cart'),
    path('remove_cart_item/<int:cart_item_id>/', views.remove_cart_item, name='remove_cart_item'),
    path('checkout/', views.checkout, name='checkout'),
]

core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('store/', include('store.urls')),
    path('cart/', include('cart.urls')),
    path('accounts/', include('accounts.urls')),
    path('order/', include('order.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += [path('__debug__/', include('debug_toolbar.urls'))]

    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)  # for serving media files in development

order/urls.py
from django.urls import path

from order import views

app_name = 'order'

urlpatterns = [
    path('place_order/', views.place_order, name='place_order'),
    path('payment/', views.payment, name='payment'),
    path('order_complete/', views.order_complete, name='order_complete'),
]

store/urls.py
from django.urls import path

from . import views

app_name = 'store'

urlpatterns = [
    path('', views.store, name='store'),
    path('category/<slug:category_slug>/', views.store, name='products_by_category'),
    path('category/<slug:category_slug>/<slug:product_slug>/', views.product_detail, name='product_detail'),
    path('search/', views.search_products, name='search_products'),
    path('submit_review/<int:product_id>', views.submit_review, name='submit_review')
]

order/models.py
from django.db import models
from django.utils import timezone

from accounts.models import Account
# Create your models here.
from store.models import Product, Variation


class Payment(models.Model):
    user = models.ForeignKey(Account, on_delete=models.CASCADE)
    payment_id = models.CharField(max_length=100)
    payment_method = models.CharField(max_length=100)
    amount_paid = models.CharField(max_length=100)
    status = models.CharField(max_length=100)
    created_at = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.payment_id


class Order(models.Model):
    STATUS = (
        ('New', 'New'),
        ('Accepted', 'Accepted'),
        ('Completed', 'Completed'),
        ('Cancelled', 'Cancelled')
    )

    user = models.ForeignKey(Account, on_delete=models.SET_NULL, null=True)
    payment = models.ForeignKey(Payment, on_delete=models.SET_NULL, null=True, blank=True)
    order_number = models.CharField(max_length=20)
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    phone = models.CharField(max_length=15)
    email = models.EmailField(max_length=50)
    address_line_1 = models.CharField(max_length=50)
    address_line_2 = models.CharField(max_length=50)
    country = models.CharField(max_length=50)
    state = models.CharField(max_length=50)
    city = models.CharField(max_length=50)
    order_note = models.CharField(max_length=100, blank=True)
    order_total = models.FloatField()
    tax = models.FloatField()
    status = models.CharField(max_length=10, choices=STATUS, default='New')
    ip = models.CharField(blank=True, max_length=20)
    is_ordered = models.BooleanField(default=False)
    created_at = models.DateTimeField(default=timezone.now)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        indexes = [models.Index(fields=['order_number'])]

    def get_full_name(self):
        return f"{self.first_name} {self.last_name}"

    def get_full_address(self):
        return f"{self.address_line_1} {self.address_line_2}"

    def __str__(self):
        return f"{self.order_number}"


class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    payment = models.ForeignKey(Payment, on_delete=models.SET_NULL, blank=True, null=True)
    user = models.ForeignKey(Account, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    variation = models.ManyToManyField(Variation, blank=True)
    quantity = models.IntegerField()
    product_price = models.FloatField()
    ordered = models.BooleanField(default=False)
    created_at = models.DateTimeField(default=timezone.now)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.product.product_name

order/forms.py
from django import forms

from order.models import Order


class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['first_name', 'last_name', 'email', 'phone', 'address_line_1', 'address_line_2', 'city', 'state',
                  'country', 'order_note']

order/views.py
import datetime
import json
import logging

from django.contrib.auth.decorators import login_required
from django.core.mail import EmailMessage
from django.http import HttpRequest, JsonResponse
from django.shortcuts import redirect, render
from django.template.loader import render_to_string
from django.views.decorators.http import require_POST

from cart.models import CartItem
from order.forms import OrderForm
from order.models import Order, Payment, OrderItem
from store.models import Product

logger = logging.getLogger(__file__)


@require_POST
@login_required
def place_order(request: HttpRequest):
    current_user = request.user
    cart_items = CartItem.objects.filter(buyer=current_user).prefetch_related('product')

    if cart_items.count() < 1:
        return redirect('store:store')

    form = OrderForm(request.POST)
    if form.is_valid():
        total = 0

        for cart_item in cart_items:
            total += cart_item.product.price * cart_item.quantity

        tax = (2 * total) / 100
        grand_total = total + tax

        print(form.data)
        order = Order()
        order.user = current_user
        order.first_name = form.cleaned_data['first_name']
        order.last_name = form.cleaned_data['last_name']
        order.email = form.cleaned_data['email']
        order.phone = form.cleaned_data['phone']
        order.address_line_1 = form.cleaned_data['address_line_1']
        order.address_line_2 = form.cleaned_data['address_line_2']
        order.city = form.cleaned_data['city']
        order.state = form.cleaned_data['state']
        order.country = form.cleaned_data['country']
        order.order_note = form.cleaned_data['order_note']
        order.order_total = grand_total
        order.tax = tax
        order.ip = request.META.get('REMOTE_ADDR')
        order.save()

        order_number = datetime.date.today().strftime('%Y%m%d')
        order.order_number = order_number + str(order.id)
        order.save()

        context = {
            'order': order,
            'total': total,
            'tax': tax,
            'grand_total': grand_total,
            'cart_items': cart_items,
        }

        return render(request, 'order/payment.html', context)

    return redirect('cart:checkout')


@require_POST
@login_required
def payment(request: HttpRequest):
    body = json.loads(request.body)

    order = Order.objects.get(user=request.user, order_number=body['orderID'], is_ordered=False)

    payment = Payment(
        user=request.user,
        payment_id=body['transactionID'],
        payment_method=body['paymentMethod'],
        amount_paid=order.order_total,
        status=body['status']
    )
    payment.save()

    order.payment = payment
    order.is_ordered = True
    order.save()

    # move cart items to order item table
    cart_items = CartItem.objects.filter(buyer=request.user)
    for cart_item in cart_items:
        order_item = OrderItem()
        order_item.order = order
        order_item.payment = payment
        order_item.user = request.user
        order_item.product = cart_item.product
        order_item.quantity = cart_item.quantity
        order_item.product_price = cart_item.product.price
        order_item.ordered = True

        order_item.save()

        order_item = OrderItem.objects.get(id=order_item.id)
        order_item.variation.add(*cart_item.variations.all())
        order_item.save()

        product = Product.objects.get(id=cart_item.product_id)
        product.stock -= cart_item.quantity
        product.save()

    # remove cart
    cart_items.delete()

    # notify user
    email_subject = 'Thank you for your order'
    email_body = render_to_string('order/order_receive_email.html', {'user': request.user, 'order': order})

    email_message = EmailMessage(email_subject, email_body, to=[request.user.email])
    email_message.send()
    logger.info('Order email sent.')

    # display order number and transaction number
    data = {
        'orderID': order.order_number,
        'transactionID': payment.payment_id
    }

    return JsonResponse(data)


def order_complete(request: HttpRequest):
    order_number = request.GET.get('order_number')
    transaction_number = request.GET.get('transaction_number')
    try:
        order = Order.objects.get(order_number=order_number, is_ordered=True)
        order_items = OrderItem.objects.filter(order_id=order.id)
        payment = Payment.objects.get(payment_id=transaction_number)

        total = 0
        for item in order_items:
            total += item.product.price * item.quantity

        context = {
            'order': order,
            'payment': payment,
            'order_items': order_items,
            'total': total
        }
        return render(request, 'order/order_complete.html', context)
    except (Order.DoesNotExist, Payment.DoesNotExist):
        return redirect('store:store')

templates/order/order_complete.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

  <div class="container" style="margin-top: 50px;">
    <div class="text-center"><i class="fas fa-check-circle"
                                style="font-size: 72px;margin-bottom: 20px;color: #28A745;"></i></div>
    <h2 class="text-center">Payment Successful</h2>
    <br>
    <div class="text-center">
      <a href="{% url 'store:store' %}" class="btn btn-success">Shop more</a>
    </div>
  </div>

  <div class="container"
       style="margin: 0 auto;width: 50%;padding: 50px;background: #f1f1f1;margin-top: 50px;margin-bottom: 50px;">
    <div class="row invoice row-printable">
      <div class="col-md-12">
        <!-- col-lg-12 start here -->
        <div class="panel panel-default plain" id="dash_0">
          <!-- Start .panel -->
          <div class="panel-body p30">
            <div class="row">
              <!-- Start .row -->
              <div class="col-lg-6">
                <!-- col-lg-6 start here -->
                <div class="invoice-logo"><img src="{% static '/images/logo.png' %}" alt="Invoice logo"
                                               style="max-height: 40px;">
                </div>
              </div>
              <!-- col-lg-6 end here -->
              <div class="col-lg-6">
                <!-- col-lg-6 start here -->
                <div class="invoice-from">
                  <ul class="list-unstyled text-right">
                    <li><strong>Invoiced To</strong></li>
                    <li>{{ order.get_full_name }}</li>
                    <li>{{ order.get_full_address }}</li>
                    <li>{{ order.city }}, {{ order.state }}</li>
                    <li>{{ order.country }}</li>
                  </ul>
                </div>
              </div>
              <!-- col-lg-6 end here -->
              <div class="col-lg-12">
                <!-- col-lg-12 start here -->
                <div class="invoice-details mt25">
                  <div class="well">
                    <ul class="list-unstyled mb0">
                      <li><strong>Order</strong> #{{ order.order_number }}</li>
                      <li><strong>Transaction</strong> #{{ payment.transaction_number }}</li>
                      <li><strong>Order Date:</strong> {{ order.created_at }}</li>
                      <li><strong>Status:</strong> {{ payment.status }}</li>
                    </ul>
                  </div>
                </div>

                <div class="invoice-items">
                  <div class="table-responsive" style="overflow: hidden; outline: none;" tabindex="0">
                    <table class="table table-bordered">
                      <thead>
                      <tr>
                        <th class="per70 text-center">Description</th>
                        <th class="per5 text-center">Qty</th>
                        <th class="per25 text-center">Total</th>
                      </tr>
                      </thead>
                      <tbody>
                      {% for order_item in order_items %}
                        <tr>
                          <td>{{ order_item.product.product_name }}
                            {% if order_item.variation.all %}
                              {% for variation in order_item.variation.all %}
                                <p class="text-muted small mb-0">{{ variation.variation_category | capfirst }}: {{ variation.variation_value | capfirst }}
                                  <br></p>
                              {% endfor %}
                            {% endif %}
                          </td>
                          <td class="text-center">{{ order_item.quantity }}</td>
                          <td class="text-center">${{ order_item.product_price }}</td>
                        </tr>
                      {% endfor %}

                      </tbody>
                      <tfoot>
                      <tr>
                        <th colspan="2" class="text-right">Sub Total:</th>
                        <th class="text-center">${{ total }} USD</th>
                      </tr>
                      <tr>
                        <th colspan="2" class="text-right">Tax:</th>
                        <th class="text-center">${{ order.tax }} USD</th>
                      </tr>

                      <tr>
                        <th colspan="2" class="text-right">Grand Total:</th>
                        <th class="text-center">${{ order.order_total }} USD</th>
                      </tr>
                      </tfoot>
                    </table>
                  </div>
                </div>
                <div class="invoice-footer mt25">
                  <p class="text-center">Thank you for shopping with us!</p>
                </div>
              </div>
              <!-- col-lg-12 end here -->
            </div>
            <!-- End .row -->
          </div>
        </div>
        <!-- End .panel -->
      </div>
      <!-- col-lg-12 end here -->
    </div>
  </div>

{% endblock %}

templates/order/order_receive_email.html
{% autoescape off %}
  Hi {{ user.first_name }},
  You order has been placed

  Order Number: {{ order.order_number }}

{% endautoescape %}

templates/order/payment.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
  <section class="section-content padding-y bg">
    <div class="container">

      <!-- ============================ COMPONENT 1 ================================= -->

      <div class="row">
        <aside class="col-lg-8">
          <h4 class="text-center mb-3">Review and make payment</h4>
          <div class="card mb-2">
            <h5 class="card-header">
              Billing Address
            </h5>
            <div class="card-body">
              <p class="card-text mb-0">{{ order.get_full_name }}</p>
              <p class="card-text mb-0">{{ order.get_full_address }}</p>
              <p class="card-text mb-0">{{ order.city }}, {{ order.state }}</p>
              <p class="card-text mb-0">{{ order.country }}</p>
              {% if order.order_note %}
                <p class="card-text mb-0"><b>Order Note: </b>{{ order.order_note }}</p>
              {% endif %}
              <p class="card-text mb-0">{{ order.email }}</p>
              <p class="card-text mb-0">{{ order.phone }}</p>
              </p>
            </div>
          </div> <!-- card.// -->

          <div class="card mb-2">
            <h5 class="card-header">
              Payment Method
            </h5>
            <div class="card-body">
              <p class="card-text">PayPal</p>
            </div>
          </div> <!-- card.// -->

          <div class="card">
            <h5 class="card-header">
              Review Products
            </h5>
            <div class="card-body">
              <table class="table table-borderless table-shopping-cart">
                <thead class="text-muted">
                <tr class="small text-uppercase">
                  <th scope="col">Product</th>
                  <th scope="col" width="120">Quantity</th>
                  <th scope="col" width="120">Price</th>

                </tr>
                </thead>

                <tbody>
                {% for cart_item in cart_items %}
                  <tr>
                    <td>
                      <figure class="itemside align-items-center">
                        <div class="aside"><img src="{{ cart_item.product.product_images.url }}" class="img-sm"></div>
                        <figcaption class="info">
                          <a href="{{ cart_item.product.get_url }}"
                             class="title text-dark">{{ cart_item.product.product_name }}</a>
                          {% for variation in cart_item.variations.all %}
                            <p class="text-muted small">{{ variation.variation_category | capfirst }}: {{ variation.variation_value | capfirst }}
                              <br></p>
                          {% endfor %}
                        </figcaption>
                      </figure>
                    </td>
                    <td>
                      <!-- col.// -->
                      <div class="col">
                        <div class="text-center">
                          {{ cart_item.quantity }}
                        </div> <!-- input-group.// -->
                      </div> <!-- col.// -->
                    </td>
                    <td>
                      <div class="price-wrap">
                        <var class="price">${{ cart_item.sub_total }}</var>
                        <small class="text-muted"> ${{ cart_item.product.price }} each </small>
                      </div> <!-- price-wrap .// -->
                    </td>
                  </tr>
                {% endfor %}
                </tbody>
                <tfoot>
                <tr class="text-uppercase">
                  <td>
                    <div class="text-center "><strong>Total</strong></div>
                  </td>
                  <td><!-- col.// -->
                    <div class="col">
                      <div class="text-center">
                        {{ quantity }}
                      </div> <!-- input-group.// -->
                    </div> <!-- col.// --></td>
                  <td>
                    <div class="price-wrap">
                      <var class="price">${{ total }}</var>
                    </div> <!-- price-wrap .// -->
                  </td>
                </tr>
                </tfoot>
              </table>
            </div>
          </div> <!-- card.// -->

        </aside> <!-- col.// -->

        <aside class="col-lg-4">

          <div class="card">
            <div class="card-body">
              <dl class="dlist-align">
                <dt>Total price:</dt>
                <dd class="text-right">${{ total }}</dd>
              </dl>
              <dl class="dlist-align">
                <dt>Tax:</dt>
                <dd class="text-right"> ${{ tax }}</dd>
              </dl>
              <dl class="dlist-align">
                <dt>Total:</dt>
                <dd class="text-right text-dark b"><strong>${{ grand_total }}</strong></dd>
              </dl>
              <hr>
              <p class="text-center mb-3">
                <img src="{% static 'images/misc/payments.png' %}" height="26">
              </p>
              <div id="paypal-button-container"></div>
            </div> <!-- card-body.// -->
          </div> <!-- card.// -->

        </aside> <!-- col.// -->


      </div> <!-- row.// -->

      <!-- ============================ COMPONENT 1 END .// ================================= -->

    </div> <!-- container .//  -->
  </section>
  <!-- ========================= SECTION CONTENT END// ========================= -->

  <script>


      function getCookie(name) {
          let cookieValue = null;
          if (document.cookie && document.cookie !== '') {
              const cookies = document.cookie.split(';');
              for (let i = 0; i < cookies.length; i++) {
                  const cookie = cookies[i].trim();
                  // Does this cookie string begin with the name we want?
                  if (cookie.substring(0, name.length + 1) === (name + '=')) {
                      cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                      break;
                  }
              }
          }
          return cookieValue;
      }

      const grand_total = "{{ grand_total }}"
      const url = "{% url 'order:payment' %}"
      const csrftoken = getCookie('csrftoken');
      const orderID = "{{ order.order_number }}"
      const paymentMethod = 'PayPal'
      const redirect_url = "{% url 'order:order_complete' %}"

      function initPayPalButton() {
          paypal.Buttons({
              style: {
                  shape: 'rect',
                  color: 'gold',
                  layout: 'vertical',
                  label: 'paypal',

              },

              createOrder: function (data, actions) {
                  return actions.order.create({
                      purchase_units: [{"amount": {"currency_code": "USD", "value": grand_total}}]
                  });
              },

              onApprove: function (data, actions) {
                  return actions.order.capture().then(function (orderData) {

                      // Full available details
                      console.log('Capture result', orderData, JSON.stringify(orderData, null, 2));
                      sendData();

                      function sendData() {
                          fetch(url, {
                              method: 'POST',
                              headers: {
                                  'Content-Type': 'application/json',
                                  'X-CSRFToken': csrftoken
                              },
                              body: JSON.stringify({
                                  orderID: orderID,
                                  transactionID: orderData.id,
                                  paymentMethod: paymentMethod,
                                  status: orderData.status
                              })
                          })
                              .then((response) => response.json())
                              .then((data) => {
                                      console.log(data);
                                      console.log('Transaction complete')
                                      window.location.href = redirect_url + '?order_number=' + data.orderID + '&transaction_number=' + data.transactionID
                                  }
                              );
                      }

                      // Show a success message within this page, e.g.
                      const element = document.getElementById('paypal-button-container');
                      element.innerHTML = '';
                      element.innerHTML = '<h3>Thank you for your payment!</h3>';

                      // Or go to another URL:  actions.redirect('thank_you.html');

                  });
              },

              onError: function (err) {
                  console.log(err);
              }
          }).render('#paypal-button-container');
      }

      initPayPalButton();
  </script>
{% endblock %}